#!/usr/bin/env bash
set -euo pipefail
echo "==> Start AutoBuild ----------------------------------------------------------------
"

export OS_VER=fedora-43-aarch64
export SPECFILE="$(realpath "$1")"
export BUILD_CMD="mx-rpm -c $OS_VER --copr $COPR"
export BRANCH="HEAD"

export NAME=$(rpmspec -P "$SPECFILE" | awk '/^Name:/ {print $2; exit}')
export VERSION=$(rpmspec -P "$SPECFILE" | awk '/^Version:/ {print $2; exit}')
export SRC0=$(rpmspec -P "$SPECFILE" | awk '/^Source0:/ { sub(/^Source0:[ \t]*/, "", $0); print; exit }')
case "$SRC0" in
    */-/archive/*) REPO_URL="${SRC0%/-/archive/*}" ;;
    */archive/*)   REPO_URL="${SRC0%/archive/*}" ;;
    *)             REPO_URL="${SRC0%/*}" ;;
esac

echo "==> SPECFILE:     $SPECFILE"
echo "==> NVR:          $NAME-$VERSION"
echo "==> BASE URL:     $REPO_URL"
echo "==> COPR REPO:    $COPR
"
export current_commit=$(grep -E '^%global[[:space:]]+commit[[:space:]]+' "$SPECFILE" | awk '{print $3}')
if [[ -z "${current_commit:-}" ]]; then
    echo "==> No commit found in specfile — exiting."; echo "------------------------------------------------------------------------------------
" >&2
    exit 1
fi

export latest_commit=$(git ls-remote "$REPO_URL" "$BRANCH" | awk '{print $1}')
if [[ -z "${latest_commit:-}" ]]; then
    echo "==> Failed to get latest commit from $REPO_URL $BRANCH"; echo "------------------------------------------------------------------------------------
" >&2
    exit 1
fi

if [[ "$latest_commit" == "$current_commit" ]]; then
    echo "==> No new upstream commit (still $current_commit). Nothing to do."; echo "------------------------------------------------------------------------------------
"
    exit 0
fi

echo "==> New commit detected:"
echo "==>   old: $current_commit"
echo "==>   new: $latest_commit
"
perl -pi -e '
    if (/^%global\s+commit\s+[0-9a-f]{7,40}\s*$/) {
        s/([0-9a-f]{7,40})/'"$latest_commit"'/;
    }
' "$SPECFILE"


perl -pi -e '
  if (/^%global\s+bumpver\s+(\d+)\s*$/) {
      $n = $1 + 1;
      s/%global\s+bumpver\s+\d+/%global bumpver $n/;
  }
' "$SPECFILE"

VR=$(rpmspec -q --srpm --qf '%{version}-%{release}\n' "$SPECFILE" | head -n1)
VR=${VR%.*}

entry=$(printf '* %s %s - %s\n - Update to commit %s\n' \
    "$(LC_ALL=C date '+%a %b %d %Y')" \
    "$(rpmdev-packager)" \
    "$VR" \
    "$latest_commit")

ENTRY="$entry" perl -0pi -e '
    my $entry = $ENV{ENTRY} . "\n";
    s/^(%changelog\s*\n)/$1$entry\n/m;
' "$SPECFILE"

echo "==> Running AutoBuild: "${BUILD_CMD}" $SPECFILE"

$BUILD_CMD $SPECFILE
echo "------------------------------------------------------------------------------------
"
