export default async (call) => {
  const expect = async (p, want) => { const out = await p; if (!out.includes(want)) console.log(`FAIL: expected ${JSON.stringify(want)}`); };
  const L = () => call("evaluate", { code: "log.splice(0).join(' ')" });
  await call("tab_new", { url: "http://127.0.0.1:8000/csp.html" });
  await expect(call("read_page", { filter: "interactive" }), '[redacted]');
  await call("click", { selector: "#b" }); await expect(L(), "click:b:T:d1");
  await call("click", { selector: "#b", button: 2, modifiers: "shift" }); await expect(L(), "auxclick:b:T:d1:b2:shift");
  await call("click", { selector: "#para", count: 3 }); await expect(call("evaluate", { code: "getSelection().toString()" }), "Triple click selects"); await L();
  await call("type", { selector: "#t", text: "Hello" }); await call("type", { selector: "#t", text: " there", clear: false }); await expect(call("evaluate", { code: "t.value" }), "Hello there"); await L();
  await call("press_key", { key: "ctrl+a Backspace" }); await call("press_key", { key: "x", repeat: 3 }); await expect(call("evaluate", { code: "JSON.stringify(t.value)" }), '"xxx"');
  await call("type", { selector: "#ce", text: "rich\ntext" }); await expect(call("evaluate", { code: "JSON.stringify(ce.innerText)" }), "rich\\ntext");
  await call("type", { selector: "#dt", text: "2026-10-03" }); await expect(call("evaluate", { code: "dt.value" }), "2026-10-03");
  await call("form_input", { selector: "#s", value: "Two" }); await call("form_input", { selector: "#cb", value: true }); await expect(call("evaluate", { code: "[s.value, cb.checked].join()" }), "2,true");
  await expect(call("scroll", { x: 151, y: 163, amount: 200 }), '"scrollTop": 200'); await call("scroll", {}); await call("scroll", { direction: "top" });
  await call("drag", { selector: "#drag", toX: 600, toY: 300 }); await expect(call("evaluate", { code: "[drag.style.left, drag.style.top].join()" }), "570px,270px");
  await L();
  await call("drag", { selector: "#src", toSelector: "#dst" }); await expect(call("evaluate", { code: "dst.textContent" }), "dropped");
  const after = await L(); if (!after.includes("drop:payload:T") || after.includes("click")) console.log("FAIL: drop events " + after);
  await call("hover", { selector: "#b" }); await expect(L(), "mouseover:b:T");
  await expect(call("evaluate", { code: "await new Promise(r => setTimeout(r, 10)); window.secret" }), "42");
  await expect(call("console_logs", { pattern: "XYZ" }), "boot error xyz");
  await expect(call("get_text", {}), "Main body text.");
  await expect(call("read_page", { selector: "main" }), "1 elements");
  await expect(call("read_page", { filter: "interactive" }), "draggable");
  await call("click", { ref: "e1" }); await expect(L(), "click:b:T");
  await call("screenshot", {});
  await expect(call("screenshot", { region: [0, 0, 300, 100] }), "zoom 4.00x");
  await call("navigate", { url: "https://127.0.0.1:8000/csp.html" });
  await expect(call("press_key", { key: "Tab" }), "doesn't match");
};
